<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8">
    <title>{{ __('Periodic report') }} — {{ $rapport->etudiant?->nom_complet_ar }}</title>
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { font-size: 12px; color: #111; margin: 0; }
        h1 { font-size: 18px; text-align: center; margin: 0 0 2px; }
        .sub { text-align: center; color: #555; font-size: 11px; margin-bottom: 16px; }
        .badge { display: inline-block; padding: 1px 8px; border: 1px solid #999; border-radius: 10px; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
        th, td { border: 1px solid #999; padding: 4px 8px; font-size: 11px; text-align: right; }
        th { background: #ececec; }
        .hdr td { border: none; padding: 2px 0; }
        .hdr b { display: inline-block; min-width: 90px; }
        .center { text-align: center; }
        .totals td { border: none; text-align: right; padding: 2px 8px; }
        .footer { text-align: center; color: #777; font-size: 10px; margin-top: 12px; }
        .empty { color: #888; text-align: center; }
    </style>
</head>
<body>
    <h1>{{ config('app.name') }}</h1>
    <div class="sub">{{ __('Periodic report') }}</div>

    <table class="hdr">
        <tr>
            <td class="center"><b>{{ __('Student') }}:</b> {{ $rapport->etudiant?->nom_complet_ar }}</td>
            <td class="center"><b>{{ __('Halaqa') }}:</b> {{ $rapport->groupe?->nom_ar }}</td>
            <td class="center"><b>{{ __('Period') }}:</b> {{ $rapport->date_debut->translatedFormat('d/m/Y') }} — {{ $rapport->date_fin->translatedFormat('d/m/Y') }}</td>
        </tr>
    </table>

    <table>
        <tr>
            <th>{{ __('Type') }}</th>
            <th>{{ __('Sessions') }}</th>
            <th>{{ __('Presences') }}</th>
            <th>{{ __('Absences') }}</th>
            <th>{{ __('Lateness') }}</th>
            <th>{{ __('Attendance rate') }}</th>
        </tr>
        <tr>
            <td>{{ $rapport->type->getLabel() }}</td>
            <td class="center">{{ $rapport->nb_seances }}</td>
            <td class="center">{{ $rapport->nb_presences }}</td>
            <td class="center">{{ $rapport->nb_absences }}</td>
            <td class="center">{{ $rapport->nb_retards }}</td>
            <td class="center">{{ $rapport->taux_presence !== null ? $rapport->taux_presence.'%' : '—' }}</td>
        </tr>
    </table>

    <table>
        <tr>
            <th></th>
            <th>{{ __('Memorized pages') }}</th>
            <th>{{ __('Revised pages') }}</th>
        </tr>
        <tr>
            <td>{{ __('Pages') }}</td>
            <td class="center">{{ $rapport->total_pages_hifd }}</td>
            <td class="center">{{ $rapport->total_pages_murajaa }}</td>
        </tr>
        <tr>
            <td>{{ __('Level') }}</td>
            <td class="center">{{ $rapport->moyenne_hifd?->getLabel() ?? '—' }}</td>
            <td class="center">{{ $rapport->moyenne_murajaa?->getLabel() ?? '—' }}</td>
        </tr>
    </table>

    <table class="totals">
        <tr>
            <td><b>{{ __('Behavior') }}:</b> {{ $rapport->moyenne_comportement?->getLabel() ?? '—' }}</td>
            <td><b>{{ __('Overall appreciation') }}:</b> {{ $rapport->appreciation ?? '—' }}</td>
            <td><b>{{ __('Generated by') }}:</b> {{ $rapport->generePar?->nom_ar ?? __('System') }}</td>
        </tr>
    </table>

    @if ($sessions->isNotEmpty())
        <h2 style="font-size:13px;">{{ __('Student sessions during the period') }}</h2>
        <table>
            <tr>
                <th>{{ __('Date') }}</th>
                <th>{{ __('Attendance') }}</th>
                <th>{{ __('Behavior') }}</th>
                <th>{{ __('Recited') }}</th>
            </tr>
            @foreach ($sessions as $seance)
                <tr>
                    <td>{{ $seance->date->translatedFormat('l d/m/Y') }}</td>
                    <td class="center">{{ $seance->presence?->getLabel() }}</td>
                    <td class="center">{{ $seance->note_comportement?->getLabel() ?? '—' }}</td>
                    <td>
                        @forelse ($seance->lignes as $lg)
                            {{ $lg->type->getLabel() }}: {{ $lg->sourateDebut->numero }}.{{ $lg->ayah_debut }} → {{ $lg->sourateFin->numero }}.{{ $lg->ayah_fin }}<br>
                        @empty
                            —
                        @endforelse
                    </td>
                </tr>
            @endforeach
        </table>
    @endif

    <div class="footer">{{ __('Generated by') }} {{ config('app.name') }} — {{ now()->translatedFormat('d/m/Y H:i') }}</div>
</body>
</html>